import Link from 'next/link';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';

export default function TermsPage() {
  return (
    <main className="min-h-screen flex flex-col">
      <Header />
      <div className="flex-1 max-w-2xl mx-auto px-4 py-12 w-full">
        <Link href="/" className="text-sm text-muted-foreground hover:text-foreground mb-6 inline-block">← Back</Link>
        <h1 className="text-2xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: 2026</p>

        <div className="prose prose-sm text-foreground space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">Use of the service</h2>
            <p className="text-muted-foreground">
              LastMin Notes is a study tool that turns your notes into flashcards. You may use it only for lawful study and revision. You must not use it to generate or distribute exam leaks, cheat materials, or content that violates your institution&apos;s academic integrity policy.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">Payment</h2>
            <p className="text-muted-foreground">
              Payment is processed by ToyyibPay. By paying, you agree to their terms. Refunds are subject to ToyyibPay&apos;s and our refund policy. If generation fails after payment, contact us for support.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">Disclaimer</h2>
            <p className="text-muted-foreground">
              Flashcards are generated by AI from your input. We do not guarantee accuracy or exam coverage. Use the output as a study aid only. We are not liable for any academic or other outcomes from your use of the service.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
